### ISSUE TITLE
About Subjectivity Analysis Subtask in MOSI

### ISSUE THREAD

**Issue by leo19941227** [A2Zadeh/CMU-MultimodalSDK#155] opened 2019-09-17 13:47 UTC
Hi Amir,

Thanks for the great SDK. It is really a handy tool saving me lots of time.
I have noticed that in the original paper of MOSI there is a subtask called Subjectivity Analysis, and Sentiment analysis is only conducted on subjective segments.
I am interested in both subtasks. However, I found the SDK seems to only support Sentiment Analysis, and only subjective segments are included in computational sequences. That means, if I wish to test my model on subjectivity analysis, I might need to preprocess the objective segments (from original MP4s) which belong to complementary set of subjective segments selected by SDK.
I would like to confirm if my understanding is correct. Maybe I am missing some elements that have already been documented?
Thank you very much!

**Comment by A2Zadeh** [comment] 2019-09-25 16:23
Hi @leo19941227. Apologies for the late response, there was a conference deadline this morning. 

It is great that you are interested in both :). Unfortunately, the ground-truth objectivity labels were lost a while ago during a hard drive crash. Good news is that all the subjective segments are the ones that accompany sentiment, and none other. Anything that does not contain sentiment, is therefore objective. 

That being said, you may be able to devise your own ground-truth for objectivity by splitting the transcripts into sentences and picking parts that do not have sentiment assigned to them. This is very close to the approach we took originally, since the objective portions were always a full sentence. 

Please let me know if there is any other questions or any way I can help.

**Comment by A2Zadeh** [comment] 2019-10-01 21:17
I am closing this on the assumption that the problem is solved. Please let me know if otherwise.

**Closed by A2Zadeh** 2019-10-01 21:17 UTC

**Comment by leo19941227** [comment] 2019-10-02 14:25
The issue was solved and I should have closed it.
Thanks for your kindly reply!

**Comment by A2Zadeh** [comment] 2019-10-02 15:59
@leo19941227 Best of luck to your experiments, and looking forward to your findings.
