### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by DeepInEvil** [A2Zadeh/CMU-MultimodalSDK#156] opened 2019-09-23 12:40 UTC
Can you please add the licensing?

**Comment by A2Zadeh** [comment] 2019-09-25 16:24
Hello @DeepInEvil. The SDK is already under MIT License. Do you want another license to be added? Anything specific?

**Comment by A2Zadeh** [comment] 2019-10-01 21:16
I am closing this on the assumption that the problem is solved. Please let me know if otherwise.

**Closed by A2Zadeh** 2019-10-01 21:16 UTC
