### ISSUE TITLE
opinion included in single word

### ISSUE THREAD

**Issue by ntubertchen** [A2Zadeh/CMU-MultimodalSDK#86] opened 2019-01-25 12:40 UTC
I found the following folders contain opinions express by a word.

One of them is simply a space, which is labeled 0.

The other two only contain one word. It seems to differ from the three bullet principles. Please check out on them.

aiEXnCPZubE words:569 labels:27
9qR7uwkblbs words:722 labels:32
2WGyTLYerpo words:484 labels:43

**Comment by A2Zadeh** [comment] 2019-01-25 17:55
Hmm I am not sure I fully understood the question. You are saying that some segments are one word only? That can be the case for example if someone says "OK" in a happy tone. That by itself is a sentence if separated by dots on both sides.

**Comment by A2Zadeh** [comment] 2019-01-29 07:58
@ntubertchen I am a bit confused about opinion for words. CMU-MOSEI has annotations per sentence but not words. If I understand correctly, there is only one word in some sentences and that's how there is one-word assignment of opinion (for example sentiment value)?

**Comment by A2Zadeh** [comment] 2019-02-02 05:14
I assume thumbs up means the issue is resolved? I will close it for now, feel free to respond on the same issue.

**Closed by A2Zadeh** 2019-02-02 05:14 UTC
